# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@1
  displayName: Container registry login
  inputs:
    command: login
    dockerRegistryEndpoint: camino.azurecr.io
    containerRegistryType: Container Registry

- task: DownloadSecureFile@1
  name: caCertificate
  displayName: 'Download settings.xml'
  inputs:
    secureFile: 'settings.xml'

- task: MavenAuthenticate@0
  displayName: 'Maven Authenticate'
  inputs:
    artifactsFeeds: che-dashboard

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'deploy'

- script: |
    docker build -t camino.azurecr.io/camino/che-dashboard:next -f apache.Dockerfile .
  displayName: Building image.

- script: |
    docker push camino.azurecr.io/camino/che-dashboard:next
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  displayName: Pushing image.
